# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5c556b96ed98d2402468002ef4ef817858ab0cdd0383aa2553a421a9fb789959dce6ed62c51f915f3ff451777c70ba37517c76223e9f165489187597342645

test:
  secret_key_base: cae49e8c82826cc106b4da69d40ff3ff66f43ceabc08565bc15bff04dfa9afe93c383c4b098193e8764cd60210d0c103644e5e0a4038dec9c9c01983231d09b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
